# Generated by Django 5.2.1 on 2025-06-27 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DietType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('non_vegetarian', 'Non-Vegetarian'), ('pescatarian', 'Pescatarian'), ('keto', 'Keto'), ('paleo', 'Paleo'), ('open', 'Open to All')], max_length=30, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='calories',
            field=models.PositiveIntegerField(blank=True, help_text='Approximate calorie content', null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='contains_dairy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='contains_gluten',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='contains_nuts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='taste_tags',
            field=models.CharField(blank=True, help_text='e.g. spicy, tangy, sweet', max_length=255),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cuisine',
            field=models.CharField(blank=True, help_text='e.g. Indian, Italian', max_length=100),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='steps',
            field=models.TextField(help_text='Instructions in plain text or markdown'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who created this recipe', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipe',
            name='suitable_for_diet_types',
            field=models.ManyToManyField(blank=True, help_text='Which diets this recipe suits e.g. Vegan, Keto', to='recipes.diettype'),
        ),
    ]
