# Generated by Django 5.2.1 on 2025-06-30 16:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipecomment_recipenutrition_recipebookmark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=cloudinary.models.CloudinaryField(default=1, help_text='Main image of the recipe. Required.', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Optional video showing how to prepare the recipe', max_length=255, null=True, verbose_name='video'),
        ),
    ]
